### ISSUE TITLE
GetGameLogs not working

### ISSUE THREAD

**Issue by johnricco** [ccagrawal/sportsTools#2]
`GetGameLogs` is not working right now. Something might be up with the API -- 'http://stats.nba.com/player/' does not load.

**Comment by ccagrawal** [comment]
Thanks for pointing this out. NBA.com must have changed their API requiring the User Agent to be specified. I added this in all the calls. The following works now:

```
sportsTools::GetGameLog(player = 'James Harden', year = 2015)
```
